### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by tenacious** [CloudInvent/Cheetah.Examples#1]
Hello, 
i'm trying to contact you for more information about commercial license and other issue , but i didn't get any reply . Is this mail address still active _support@cloud-invent.com_ , _info@cloud-invent.com_ ?

**Comment by Evil-Spirit** [comment]
check this https://www.youtube.com/playlist?list=PLqmaFsEpxcUXzvoLdZ7QtpKb_iInqo1pT

**Comment by tenacious** [comment]
Hello Alexey,

Do you have any .Net wrapper for that ?
Price for commercial use ?

2016-09-12 18:50 GMT+02:00 Alexey Egorov notifications@github.com:

**Comment by CloudInvent** [comment]
Hello!

Yes, these addresses are active, but you can write directly to me:
dmitry@cloud-invent.com. It will be much faster.

Please, describe your requirements for a better understanding of what you
need from us and what we can provide for you. Anyway, before we will launch
commercial release (spring of 2017) of our solver, we will not take any
money, and you are able to try to integrate our solution into your
application without any charges (with appropriate NDA contract).

Also, consider that our GitHub version is old, and now we have much faster
and much stable release. We are launching stable releases each three
months, and latest was launched 31 of august. We are focused on launching a
commercial version in next 6 months, so we freeze a little bit our GitHub.
If you are interested in trying our latest release - just write.

I forwarded your e-mails to my partner Nick, so you can talk with him
(nick@cloud-invent) also.

Sincere regards,

Dmitry Ratner

12 сент. 2016 г. 7:34 PM пользователь "tenacious" notifications@github.com
написал:
